/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":infrastructure"))
    // Spring Web is required to enable MVC test infrastructure in integration tests
    implementation("org.springframework.boot:spring-boot-starter-web:3.2.12")

    // Testing utilities (MockMvc, SpringBootTest, JUnit, AssertJ)
    testImplementation("org.springframework.boot:spring-boot-starter-test:3.2.12")
}

application {
}
