/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    implementation(project(":domain"))

    // Spring Data JPA for repository implementations
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:3.2.6")

    // H2 in-memory database for tests and local runs
    runtimeOnly("com.h2database:h2:2.2.220")

    testImplementation("org.springframework.boot:spring-boot-starter-test:3.2.6")
}
